//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalInfo
    {
        public int id { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public string opentime { get; set; }
        public string email { get; set; }
        public string meta { get; set; }
        public Nullable<bool> hide { get; set; }
        public Nullable<int> order { get; set; }
        public Nullable<System.DateTime> datebegin { get; set; }
    }
}
